name: tandrustito
description: tandrustito
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.2.3
  device_preview: ^1.1.0
  iconify_flutter: ^0.0.5
  dartz: ^0.10.1
  flutter_secure_storage: ^7.0.1
  url_launcher: ^6.1.8
  dio: ^4.0.6
  fluttertoast: ^8.1.2
  google_api_availability: ^3.0.1
  connectivity_plus: ^3.0.2
  equatable: ^2.0.5
  flutter_map: ^3.1.0
  awesome_dialog: ^3.0.2
  flutter_svg:
  location: ^4.4.0
  app_settings: ^4.2.0
  uuid: ^3.0.7

  huawei_location: ^6.4.0+300
  permission_handler: ^10.2.0
  image_picker: ^0.8.6+1
  provider: ^6.0.5
  path_provider: ^2.0.12
  image_editor: ^1.3.0
  bubble: ^1.2.1
  extended_image: 
  flutter_slidable: ^2.0.0
  salomon_bottom_bar: ^3.3.1
  map_launcher: ^2.4.0
  latlong2: ^0.8.1
  device_info_plus: ^8.0.0
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.11
  firebase_database: ^10.0.9
dev_dependencies:
  flutter_native_splash:
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/i18n/
flutter_native_splash:
  color: "#FFFFFF"
  android_12:
    image: assets/images/logo.jpg
    color_dark: "#FFFFFF"
  image: assets/images/logo.jpg
  color_dark: "#FFFFFF"
  image_dark: assets/images/logo.jpg
  android: true
  ios: true
